import { NextRequest, NextResponse } from "next/server";

export const runtime = "edge";

interface PushBody {
  repo: string;
  branch?: string;
  commitMessage?: string;
  createIfMissing?: boolean;
  privateRepo?: boolean;
  files: { path: string; content: string }[];
}

async function gh(
  token: string,
  path: string,
  init: RequestInit = {}
): Promise<Response> {
  return fetch(`https://api.github.com${path}`, {
    ...init,
    headers: {
      Accept: "application/vnd.github+json",
      Authorization: `token ${token}`,
      "X-GitHub-Api-Version": "2022-11-28",
      "User-Agent": "njirlah-ai",
      ...(init.headers || {}),
    },
  });
}

async function getUserLogin(token: string): Promise<string> {
  const r = await gh(token, "/user");
  if (!r.ok) throw new Error(`auth failed: ${r.status}`);
  const j = await r.json();
  return j.login as string;
}

async function ensureRepo(
  token: string,
  owner: string,
  repo: string,
  createIfMissing: boolean,
  privateRepo: boolean
): Promise<void> {
  const r = await gh(token, `/repos/${owner}/${repo}`);
  if (r.ok) return;
  if (r.status !== 404 || !createIfMissing) {
    throw new Error(`repo check failed: ${r.status}`);
  }
  const c = await gh(token, "/user/repos", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      name: repo,
      private: privateRepo,
      auto_init: true,
      description: "Generated by NJIRLAH AI",
    }),
  });
  if (!c.ok) {
    const t = await c.text();
    throw new Error(`create repo failed: ${c.status} ${t}`);
  }
}

async function getDefaultBranch(
  token: string,
  owner: string,
  repo: string
): Promise<string> {
  const r = await gh(token, `/repos/${owner}/${repo}`);
  const j = await r.json();
  return (j.default_branch as string) || "main";
}

async function getRef(
  token: string,
  owner: string,
  repo: string,
  branch: string
): Promise<{ sha: string; treeSha: string } | null> {
  const r = await gh(
    token,
    `/repos/${owner}/${repo}/git/ref/heads/${encodeURIComponent(branch)}`
  );
  if (r.status === 404 || r.status === 409) return null;
  if (!r.ok) throw new Error(`ref lookup failed: ${r.status}`);
  const j = await r.json();
  const commitSha = j.object.sha as string;
  const cr = await gh(token, `/repos/${owner}/${repo}/git/commits/${commitSha}`);
  const cj = await cr.json();
  return { sha: commitSha, treeSha: cj.tree.sha };
}

async function createBlob(
  token: string,
  owner: string,
  repo: string,
  content: string
): Promise<string> {
  const r = await gh(token, `/repos/${owner}/${repo}/git/blobs`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ content, encoding: "utf-8" }),
  });
  if (!r.ok) throw new Error(`blob failed: ${r.status}`);
  const j = await r.json();
  return j.sha as string;
}

export async function POST(req: NextRequest) {
  try {
    const token = req.headers.get("x-github-token") || "";
    if (!token) {
      return NextResponse.json(
        { error: "missing x-github-token header" },
        { status: 401 }
      );
    }

    const body = (await req.json()) as PushBody;
    const {
      repo,
      branch = "main",
      commitMessage = "chore: sync from NJIRLAH AI",
      createIfMissing = true,
      privateRepo = true,
      files,
    } = body;

    if (!repo || !files?.length) {
      return NextResponse.json(
        { error: "repo and files are required" },
        { status: 400 }
      );
    }

    const owner = await getUserLogin(token);
    await ensureRepo(token, owner, repo, createIfMissing, privateRepo);
    const defaultBranch = await getDefaultBranch(token, owner, repo);
    const targetBranch = branch || defaultBranch;

    let parent = await getRef(token, owner, repo, targetBranch);
    if (!parent) {
      parent = await getRef(token, owner, repo, defaultBranch);
    }

    const treeItems: {
      path: string;
      mode: "100644";
      type: "blob";
      sha: string;
    }[] = [];

    for (const f of files) {
      const sha = await createBlob(token, owner, repo, f.content);
      treeItems.push({
        path: f.path.replace(/^\/+/, ""),
        mode: "100644",
        type: "blob",
        sha,
      });
    }

    const treeRes = await gh(token, `/repos/${owner}/${repo}/git/trees`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        base_tree: parent?.treeSha,
        tree: treeItems,
      }),
    });
    if (!treeRes.ok) {
      const t = await treeRes.text();
      throw new Error(`tree failed: ${treeRes.status} ${t}`);
    }
    const treeJson = await treeRes.json();

    const commitRes = await gh(token, `/repos/${owner}/${repo}/git/commits`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        message: commitMessage,
        tree: treeJson.sha,
        parents: parent ? [parent.sha] : [],
      }),
    });
    if (!commitRes.ok) {
      const t = await commitRes.text();
      throw new Error(`commit failed: ${commitRes.status} ${t}`);
    }
    const commitJson = await commitRes.json();

    const refPath = `/repos/${owner}/${repo}/git/refs/heads/${encodeURIComponent(
      targetBranch
    )}`;
    const refExistsRes = await gh(token, refPath.replace("/refs/", "/ref/"));
    let refRes: Response;
    if (refExistsRes.ok) {
      refRes = await gh(token, refPath, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ sha: commitJson.sha, force: false }),
      });
    } else {
      refRes = await gh(token, `/repos/${owner}/${repo}/git/refs`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          ref: `refs/heads/${targetBranch}`,
          sha: commitJson.sha,
        }),
      });
    }
    if (!refRes.ok) {
      const t = await refRes.text();
      throw new Error(`ref update failed: ${refRes.status} ${t}`);
    }

    return NextResponse.json({
      ok: true,
      owner,
      repo,
      branch: targetBranch,
      commit: commitJson.sha,
      url: `https://github.com/${owner}/${repo}/tree/${targetBranch}`,
    });
  } catch (e) {
    return NextResponse.json(
      { error: (e as Error).message || "push failed" },
      { status: 500 }
    );
  }
}
